"""added column comment

Revision ID: 2c3b27fdbd44
Revises: 21a90cac6b87
Create Date: 2018-09-07 14:57:51.101941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3b27fdbd44'
down_revision = '21a90cac6b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_comment', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_id')
    op.drop_column('pitches', 'pitch_comment')
    # ### end Alembic commands ###
