"""added likes column

Revision ID: 2fe248dd5f54
Revises: 03a1beebc3be
Create Date: 2018-09-08 18:16:23.749081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe248dd5f54'
down_revision = '03a1beebc3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'likes')
    # ### end Alembic commands ###
