"""linking tables

Revision ID: fff47099e247
Revises: bd25c7a3b19d
Create Date: 2018-09-09 13:19:01.580700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff47099e247'
down_revision = 'bd25c7a3b19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['pitch_author'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'pitch_author')
    # ### end Alembic commands ###
